// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnakeCaseNaming.Module;

#nullable disable

namespace SnakeCaseNaming.Module.Migrations;

[DbContext(typeof(MembershipDbContext))]
partial class MembershipDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260719200807_InitialMembership";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("membership")
            .HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SnakeCaseNaming.Module.DoseLogEntry", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<decimal>("AmountTaken")
                    .HasPrecision(9, 3)
                    .HasColumnType("numeric(9,3)")
                    .HasColumnName("amount_taken");

                b.Property<Guid>("MedicationProfileId")
                    .HasColumnType("uuid")
                    .HasColumnName("medication_profile_id");

                b.Property<DateTimeOffset>("TakenAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("taken_at_utc");

                b.HasKey("Id")
                    .HasName("pk_dose_log_entries");

                b.HasIndex("MedicationProfileId", "TakenAtUtc")
                    .HasDatabaseName("ix_dose_log_entries_medication_profile_id_taken_at_utc");

                b.ToTable("dose_log_entries", "membership");
            });

        modelBuilder.Entity("SnakeCaseNaming.Module.MedicationProfile", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("DailyDoseLimit")
                    .HasColumnType("integer")
                    .HasColumnName("daily_dose_limit");

                b.Property<bool>("IsArchived")
                    .HasColumnType("boolean")
                    .HasColumnName("is_archived");

                b.Property<string>("ProfileDisplayName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("profile_display_name");

                b.Property<Guid>("UserAccountId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_account_id");

                b.HasKey("Id")
                    .HasName("pk_medication_profiles");

                b.HasIndex("UserAccountId", "ProfileDisplayName")
                    .IsUnique()
                    .HasDatabaseName("ix_medication_profiles_user_account_id_profile_display_name");

                b.ToTable("medication_profiles", "membership", t =>
                    {
                        t.HasCheckConstraint("ck_medication_profiles_daily_dose_limit_positive", "daily_dose_limit > 0");
                    });
            });

        modelBuilder.Entity("SnakeCaseNaming.Module.UserAccount", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("display_name");

                b.Property<string>("ExternalUserId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("external_user_id");

                b.Property<string>("IANATimeZoneId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("iana_time_zone_id");

                b.HasKey("Id")
                    .HasName("pk_user_accounts");

                b.HasAlternateKey("ExternalUserId")
                    .HasName("ak_user_accounts_external_user_id");

                b.HasIndex("DisplayName")
                    .IsUnique()
                    .HasDatabaseName("ix_user_accounts_display_name");

                b.ToTable("user_accounts", "membership");
            });

        modelBuilder.Entity("SnakeCaseNaming.Module.DoseLogEntry", b =>
            {
                b.HasOne("SnakeCaseNaming.Module.MedicationProfile", "MedicationProfile")
                    .WithMany("DoseLogEntries")
                    .HasForeignKey("MedicationProfileId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_dose_log_entries_medication_profiles_medication_profile_id");

                b.Navigation("MedicationProfile");
            });

        modelBuilder.Entity("SnakeCaseNaming.Module.MedicationProfile", b =>
            {
                b.HasOne("SnakeCaseNaming.Module.UserAccount", "UserAccount")
                    .WithMany("MedicationProfiles")
                    .HasForeignKey("UserAccountId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_medication_profiles_user_accounts_user_account_id");

                b.Navigation("UserAccount");
            });

        modelBuilder.Entity("SnakeCaseNaming.Module.UserAccount", b =>
            {
                b.OwnsOne("SnakeCaseNaming.Module.ContactDetails", "PrimaryContact", b1 =>
                    {
                        b1.Property<Guid>("UserAccountId")
                            .HasColumnType("uuid")
                            .HasColumnName("id");

                        b1.Property<string>("EmailAddress")
                            .IsRequired()
                            .HasColumnType("text")
                            .HasColumnName("primary_contact_email_address");

                        b1.Property<string>("MobilePhoneNumber")
                            .HasColumnType("text")
                            .HasColumnName("primary_contact_mobile_phone_number");

                        b1.HasKey("UserAccountId");

                        b1.ToTable("user_accounts", "membership");

                        b1.WithOwner()
                            .HasForeignKey("UserAccountId")
                            .HasConstraintName("fk_user_accounts_user_accounts_id");
                    });

                b.Navigation("PrimaryContact")
                    .IsRequired();
            });

        modelBuilder.Entity("SnakeCaseNaming.Module.MedicationProfile", b =>
            {
                b.Navigation("DoseLogEntries");
            });

        modelBuilder.Entity("SnakeCaseNaming.Module.UserAccount", b =>
            {
                b.Navigation("MedicationProfiles");
            });
#pragma warning restore 612, 618
    }
}
