// <auto-generated />
using System;
using DoseUp.Api.Modules.Membership.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoseUp.Api.Modules.Membership.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MembershipDbContext))]
partial class MembershipDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260719214415_InitialMembership";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("membership")
            .HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("DoseUp.Api.Modules.Membership.Domain.Account", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("display_name");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("email");

                b.Property<Guid>("EntraObjectId")
                    .HasColumnType("uuid")
                    .HasColumnName("entra_object_id");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.HasKey("Id")
                    .HasName("pk_accounts");

                b.HasIndex("EntraObjectId")
                    .IsUnique()
                    .HasDatabaseName("ix_accounts_entra_object_id");

                b.ToTable("accounts", "membership");
            });
#pragma warning restore 612, 618
    }
}
